/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/upload/dataset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Dataset */
        post: operations["upload_dataset_api_upload_dataset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preparation/dataset/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset Status */
        get: operations["get_dataset_status_api_preparation_dataset_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preparation/dataset/names": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset Names */
        get: operations["get_dataset_names_api_preparation_dataset_names_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preparation/dataset/processed/names": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Processed Dataset Names */
        get: operations["get_processed_dataset_names_api_preparation_dataset_processed_names_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preparation/dataset/metadata/{dataset_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Processing Metadata */
        get: operations["get_processing_metadata_api_preparation_dataset_metadata__dataset_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preparation/dataset/{dataset_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Dataset */
        delete: operations["delete_dataset_api_preparation_dataset__dataset_name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preparation/images/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Image Path */
        post: operations["validate_image_path_api_preparation_images_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preparation/dataset/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Load Dataset */
        post: operations["load_dataset_api_preparation_dataset_load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preparation/dataset/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process Dataset */
        post: operations["process_dataset_api_preparation_dataset_process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preparation/dataset/{dataset_name}/images/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset Image Count */
        get: operations["get_dataset_image_count_api_preparation_dataset__dataset_name__images_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preparation/dataset/{dataset_name}/images/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset Image Metadata */
        get: operations["get_dataset_image_metadata_api_preparation_dataset__dataset_name__images__index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preparation/dataset/{dataset_name}/images/{index}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset Image Content */
        get: operations["get_dataset_image_content_api_preparation_dataset__dataset_name__images__index__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preparation/browse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse Directory */
        get: operations["browse_directory_api_preparation_browse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training/checkpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Checkpoints */
        get: operations["get_checkpoints_api_training_checkpoints_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training/checkpoints/{checkpoint}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Checkpoint Metadata */
        get: operations["get_checkpoint_metadata_api_training_checkpoints__checkpoint__metadata_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training/checkpoints/{checkpoint}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Checkpoint */
        delete: operations["delete_checkpoint_api_training_checkpoints__checkpoint__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Training */
        post: operations["start_training_api_training_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Training */
        post: operations["resume_training_api_training_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validation/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Validation */
        post: operations["run_validation_api_validation_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validation/checkpoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate Checkpoint */
        post: operations["evaluate_checkpoint_api_validation_checkpoint_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validation/checkpoint/reports/{checkpoint}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Checkpoint Evaluation Report */
        get: operations["get_checkpoint_evaluation_report_api_validation_checkpoint_reports__checkpoint__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validation/reports/{dataset_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Validation Report */
        get: operations["get_validation_report_api_validation_reports__dataset_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inference/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Models */
        get: operations["get_models_api_inference_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inference/models/check-update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check Model Update */
        post: operations["check_model_update_api_inference_models_check_update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inference/models/maintenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Maintain Model */
        post: operations["maintain_model_api_inference_models_maintenance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inference/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Reports */
        post: operations["generate_reports_api_inference_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Cancel Job */
        delete: operations["cancel_job_api_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_generate_reports_api_inference_generate_post */
        Body_generate_reports_api_inference_generate_post: {
            /** Images */
            images: string[];
            /** Model Ref */
            model_ref: string;
            /**
             * Generation Profile
             * @enum {string}
             */
            generation_profile: "deterministic" | "concise" | "detailed";
            /**
             * Clinical Context
             * @default
             */
            clinical_context: string;
        };
        /** Body_upload_dataset_api_upload_dataset_post */
        Body_upload_dataset_api_upload_dataset_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** BrowseResponse */
        BrowseResponse: {
            /** Current Path */
            current_path: string;
            /** Parent Path */
            parent_path?: string | null;
            /** Items */
            items: components["schemas"]["DirectoryItem"][];
            /** Drives */
            drives?: string[];
        };
        /**
         * CheckpointEvaluationReportResponse
         * @description Response model for a persisted checkpoint evaluation report.
         */
        CheckpointEvaluationReportResponse: {
            /** Checkpoint */
            checkpoint: string;
            /** Date */
            date?: string | null;
            /** Metrics */
            metrics?: string[];
            /** Metric Configs */
            metric_configs?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            results?: components["schemas"]["CheckpointEvaluationResults"] | null;
        };
        /**
         * CheckpointEvaluationRequest
         * @description Request model for checkpoint evaluation.
         */
        CheckpointEvaluationRequest: {
            /** Checkpoint */
            checkpoint: string;
            /** Metrics */
            metrics: string[];
            /** Num Samples */
            num_samples: number;
            /** Metric Configs */
            metric_configs?: {
                [key: string]: {
                    [key: string]: number;
                };
            } | null;
            /** Seed */
            seed?: number | null;
        };
        /**
         * CheckpointEvaluationResults
         * @description Evaluation metric results.
         */
        CheckpointEvaluationResults: {
            /** Loss */
            loss?: number | null;
            /** Accuracy */
            accuracy?: number | null;
            /** Bleu Score */
            bleu_score?: number | null;
        };
        /** CheckpointInfo */
        CheckpointInfo: {
            /** Name */
            name: string;
            /** Epochs */
            epochs?: number | null;
            /** Loss */
            loss?: number | null;
            /** Val Loss */
            val_loss?: number | null;
            /**
             * Artifact Status
             * @default ready
             */
            artifact_status: string;
            /** Message */
            message?: string | null;
        };
        /** CheckpointMetadataResponse */
        CheckpointMetadataResponse: {
            /** Checkpoint */
            checkpoint: string;
            /** Configuration */
            configuration: {
                [key: string]: unknown;
            };
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Session */
            session: {
                [key: string]: unknown;
            };
        };
        /** CheckpointsResponse */
        CheckpointsResponse: {
            /** Checkpoints */
            checkpoints: components["schemas"]["CheckpointInfo"][];
        };
        /** DatasetInfo */
        DatasetInfo: {
            /** Name */
            name: string;
            /** Folder Path */
            folder_path: string;
            /** Row Count */
            row_count: number;
            /**
             * Has Validation Report
             * @default false
             */
            has_validation_report: boolean;
        };
        /** DatasetNamesResponse */
        DatasetNamesResponse: {
            /** Datasets */
            datasets: components["schemas"]["DatasetInfo"][];
            /** Count */
            count: number;
        };
        /** DatasetStatusResponse */
        DatasetStatusResponse: {
            /** Has Data */
            has_data: boolean;
            /** Row Count */
            row_count: number;
            /** Allow Server Browse */
            allow_server_browse: boolean;
            /** Message */
            message: string;
        };
        /** DatasetUploadResponse */
        DatasetUploadResponse: {
            /** Success */
            success: boolean;
            /** Upload Id */
            upload_id: string;
            /** Filename */
            filename: string;
            /** Dataset Name */
            dataset_name: string;
            /** Row Count */
            row_count: number;
            /** Column Count */
            column_count: number;
            /** Columns */
            columns: string[];
            /** Message */
            message: string;
        };
        /** DeleteResponse */
        DeleteResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
        };
        /** DirectoryItem */
        DirectoryItem: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Is Dir */
            is_dir: boolean;
            /**
             * Image Count
             * @default 0
             */
            image_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImageCountResponse */
        ImageCountResponse: {
            /** Dataset Name */
            dataset_name: string;
            /** Count */
            count: number;
        };
        /** ImageMetadataResponse */
        ImageMetadataResponse: {
            /** Dataset Name */
            dataset_name: string;
            /** Index */
            index: number;
            /** Image Name */
            image_name: string;
            /** Caption */
            caption: string;
            /** Valid Path */
            valid_path: boolean;
            /** Path */
            path: string;
        };
        /** ImagePathRequest */
        ImagePathRequest: {
            /**
             * Folder Path
             * @description Server-side folder path containing images
             */
            folder_path: string;
        };
        /** ImagePathResponse */
        ImagePathResponse: {
            /** Valid */
            valid: boolean;
            /** Folder Path */
            folder_path: string;
            /** Image Count */
            image_count: number;
            /** Message */
            message: string;
        };
        /**
         * ImageStatistics
         * @description Model for image statistics.
         */
        ImageStatistics: {
            /** Count */
            count: number;
            /** Mean Height */
            mean_height: number;
            /** Mean Width */
            mean_width: number;
            /** Mean Pixel Value */
            mean_pixel_value: number;
            /** Std Pixel Value */
            std_pixel_value: number;
            /** Mean Noise Std */
            mean_noise_std: number;
            /** Mean Noise Ratio */
            mean_noise_ratio: number;
        };
        /** InferenceModelsResponse */
        InferenceModelsResponse: {
            /** Models */
            models: components["schemas"]["ModelAvailability"][];
            /** Providers */
            providers: {
                [key: string]: components["schemas"]["ProviderAvailability"];
            };
        };
        /** JobCancelResponse */
        JobCancelResponse: {
            /** Job Id */
            job_id: string;
            /** Success */
            success: boolean;
            /** Message */
            message: string;
        };
        /** JobListResponse */
        JobListResponse: {
            /** Jobs */
            jobs: components["schemas"]["JobStatusResponse"][];
        };
        /** JobStartResponse */
        JobStartResponse: {
            /** Job Id */
            job_id: string;
            /** Job Type */
            job_type: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed" | "cancelled";
            /** Message */
            message: string;
            /**
             * Poll Interval
             * @default 1
             */
            poll_interval: number;
        };
        /** JobStatusResponse */
        JobStatusResponse: {
            /** Job Id */
            job_id: string;
            /** Job Type */
            job_type: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed" | "cancelled";
            /** Progress */
            progress: number;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
        };
        /** LoadDatasetRequest */
        LoadDatasetRequest: {
            /**
             * Upload Id
             * @description Explicit upload identifier returned by the dataset upload endpoint
             */
            upload_id: string;
            /**
             * Image Folder Path
             * @description Folder path containing X-ray images
             */
            image_folder_path: string;
            /**
             * Sample Size
             * @description Fraction of data to use
             */
            sample_size: number;
            /**
             * Confirm Unmatched
             * @description Explicitly confirm importing matched rows when some images are unmatched
             */
            confirm_unmatched: boolean;
        };
        /** LoadDatasetResponse */
        LoadDatasetResponse: {
            /** Success */
            success: boolean;
            /** Total Images */
            total_images: number;
            /** Matched Records */
            matched_records: number;
            /** Unmatched Records */
            unmatched_records: number;
            /**
             * Requires Confirmation
             * @default false
             */
            requires_confirmation: boolean;
            /**
             * Partial Import
             * @default false
             */
            partial_import: boolean;
            /** Message */
            message: string;
        };
        /** ModelAvailability */
        ModelAvailability: {
            /** Model Ref */
            model_ref: string;
            /**
             * Provider
             * @enum {string}
             */
            provider: "huggingface" | "xreport";
            /**
             * Origin
             * @default public
             * @enum {string}
             */
            origin: "public" | "custom";
            /** Display Name */
            display_name: string;
            /** Description */
            description: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_installed" | "unvalidated" | "downloading" | "gated" | "runtime_unavailable" | "incompatible" | "disabled";
            /** Status Message */
            status_message?: string | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Validation Status
             * @default pending
             * @enum {string}
             */
            validation_status: "blocked" | "incompatible" | "disabled" | "pending" | "degraded" | "passed";
            /** Validation Message */
            validation_message?: string | null;
            /**
             * Validation Receipt Status
             * @default missing
             * @enum {string}
             */
            validation_receipt_status: "missing" | "passed" | "invalid";
            /** Validation Receipt Message */
            validation_receipt_message?: string | null;
            /** Category */
            category: string;
            /**
             * Recommended
             * @default false
             */
            recommended: boolean;
            /**
             * Research Only
             * @default true
             */
            research_only: boolean;
            /**
             * Gated
             * @default false
             */
            gated: boolean;
            /**
             * Access Policy
             * @default open
             * @enum {string}
             */
            access_policy: "open" | "gated";
            /** Access Url */
            access_url?: string | null;
            /**
             * Anatomy Coverage
             * @default chest_xray
             */
            anatomy_coverage: string;
            /** Coverage Note */
            coverage_note?: string | null;
            /**
             * Hardware Demand
             * @default moderate
             * @enum {string}
             */
            hardware_demand: "low" | "moderate" | "high" | "very_high";
            /** Parameter Label */
            parameter_label?: string | null;
            /** Parameter Size */
            parameter_size?: string | null;
            /** Download Size Bytes */
            download_size_bytes?: number | null;
            /** Local Size Bytes */
            local_size_bytes?: number | null;
            /**
             * Input Semantics
             * @enum {string}
             */
            input_semantics: "single_image" | "independent_images" | "single_study";
            capabilities: components["schemas"]["ModelCapabilities"];
            /** Model Revision */
            model_revision?: string | null;
            /** Model Loader */
            model_loader?: string | null;
            /** Processor Loader */
            processor_loader?: string | null;
            /** Adapter */
            adapter?: string | null;
            /**
             * Trust Remote Code
             * @default false
             */
            trust_remote_code: boolean;
            /**
             * Remote Code Approved
             * @default false
             */
            remote_code_approved: boolean;
            /** Output Sections */
            output_sections?: ("raw_report" | "findings" | "impression")[];
            /**
             * Max Current Images
             * @default 1
             */
            max_current_images: number;
            /**
             * Supports Prior Images
             * @default false
             */
            supports_prior_images: boolean;
            /**
             * Supports Clinical Context
             * @default false
             */
            supports_clinical_context: boolean;
            /**
             * Preferred Dtype
             * @default auto
             */
            preferred_dtype: string;
            /** Quantization */
            quantization?: string[];
            /** Prompt Profile */
            prompt_profile?: string | null;
            /** License */
            license?: string | null;
            resource_policy?: components["schemas"]["ModelResourcePolicy"];
            runtime_constraints?: components["schemas"]["ModelRuntimeConstraints"];
            /** Processor Repository Id */
            processor_repository_id?: string | null;
            /** Processor Revision */
            processor_revision?: string | null;
            /** Processor Files */
            processor_files?: string[];
            /**
             * Processor Target Prefix
             * @default processor
             */
            processor_target_prefix: string;
            /** Required Files */
            required_files?: string[];
            /** Weight File Sets */
            weight_file_sets?: string[][];
            /**
             * Installation State
             * @default not_installed
             * @enum {string}
             */
            installation_state: "not_installed" | "staged" | "active" | "corrupt" | "failed" | "downloading";
            /** Local Path */
            local_path?: string | null;
            /** Active Revision */
            active_revision?: string | null;
            /** Candidate Revision */
            candidate_revision?: string | null;
            /**
             * Integrity Status
             * @default unknown
             */
            integrity_status: string;
            /** Cloud Assessment */
            cloud_assessment?: {
                [key: string]: unknown;
            } | null;
            /**
             * Update Available
             * @default false
             */
            update_available: boolean;
            /** Available Actions */
            available_actions?: string[];
        };
        /** ModelCapabilities */
        ModelCapabilities: {
            /**
             * Clinical Context
             * @default false
             */
            clinical_context: boolean;
            /**
             * Prior Report
             * @default false
             */
            prior_report: boolean;
            /**
             * Multiple Current Views
             * @default false
             */
            multiple_current_views: boolean;
            /**
             * Findings
             * @default false
             */
            findings: boolean;
            /**
             * Impression
             * @default false
             */
            impression: boolean;
            /**
             * Grounding
             * @default false
             */
            grounding: boolean;
        };
        /** ModelMaintenanceRequest */
        ModelMaintenanceRequest: {
            /** Model Ref */
            model_ref: string;
            /**
             * Action
             * @enum {string}
             */
            action: "download" | "repair" | "reinstall" | "download_update" | "delete_local";
            /** Revision */
            revision?: string | null;
        };
        /** ModelResourcePolicy */
        ModelResourcePolicy: {
            /** Max Snapshot Size Bytes */
            max_snapshot_size_bytes?: number | null;
            /** Reason */
            reason?: string | null;
        };
        /** ModelRuntimeConstraints */
        ModelRuntimeConstraints: {
            /** Min Transformers */
            min_transformers?: string | null;
            /** Max Transformers Exclusive */
            max_transformers_exclusive?: string | null;
            /** Required Modules */
            required_modules?: string[];
        };
        /** ModelUpdateCheckRequest */
        ModelUpdateCheckRequest: {
            /** Model Ref */
            model_ref: string;
        };
        /** ModelUpdateCheckResponse */
        ModelUpdateCheckResponse: {
            /** Model Ref */
            model_ref: string;
            /** Repository Id */
            repository_id: string;
            /** Installed Revision */
            installed_revision?: string | null;
            /** Latest Revision */
            latest_revision?: string | null;
            /**
             * Update Available
             * @default false
             */
            update_available: boolean;
            /** Source */
            source: string;
            /** Checked At */
            checked_at: string;
            /** Error */
            error?: string | null;
        };
        /**
         * PixelDistribution
         * @description Model for pixel intensity distribution.
         */
        PixelDistribution: {
            /** Bins */
            bins: number[];
            /** Counts */
            counts: number[];
        };
        /** ProcessDatasetRequest */
        ProcessDatasetRequest: {
            /**
             * Dataset Name
             * @description Dataset name to process
             */
            dataset_name: string;
            /**
             * Custom Name
             * @description Optional custom name for the processed dataset
             */
            custom_name?: string | null;
            /**
             * Sample Size
             * @description Fraction of data to use
             */
            sample_size: number;
            /**
             * Validation Size
             * @description Fraction of data for validation
             */
            validation_size: number;
            /**
             * Tokenizer
             * @description Hugging Face tokenizer ID
             */
            tokenizer: string;
            /**
             * Max Report Size
             * @description Maximum token length for reports
             */
            max_report_size: number;
        };
        /** ProcessingMetadataResponse */
        ProcessingMetadataResponse: {
            /** Dataset Name */
            dataset_name: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** ProviderAvailability */
        ProviderAvailability: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_installed" | "unvalidated" | "downloading" | "gated" | "runtime_unavailable" | "incompatible" | "disabled";
            /** Message */
            message?: string | null;
        };
        /** ResumeTrainingRequest */
        ResumeTrainingRequest: {
            /**
             * Checkpoint
             * @description Checkpoint name to resume from
             */
            checkpoint: string;
            /**
             * Additional Epochs
             * @description Additional epochs to train
             */
            additional_epochs: number;
        };
        /** StartTrainingRequest */
        StartTrainingRequest: {
            /**
             * Dataset Name
             * @description Processed dataset name to use for training
             */
            dataset_name: string;
            /**
             * Epochs
             * @description Number of training epochs
             */
            epochs: number;
            /**
             * Batch Size
             * @description Batch size for training
             */
            batch_size: number;
            /**
             * Num Encoders
             * @description Number of encoder layers
             */
            num_encoders: number;
            /**
             * Num Decoders
             * @description Number of decoder layers
             */
            num_decoders: number;
            /**
             * Embedding Dims
             * @description Embedding dimensions
             */
            embedding_dims: number;
            /**
             * Attention Heads
             * @description Number of attention heads
             */
            attention_heads: number;
            /**
             * Train Temp
             * @description Training temperature
             */
            train_temp: number;
            /**
             * Freeze Img Encoder
             * @description Freeze image encoder weights
             */
            freeze_img_encoder: boolean;
            /**
             * Use Img Augmentation
             * @description Enable image augmentation
             */
            use_img_augmentation: boolean;
            /**
             * Shuffle With Buffer
             * @description Enable shuffle with buffer
             */
            shuffle_with_buffer: boolean;
            /**
             * Shuffle Size
             * @description Shuffle buffer size
             */
            shuffle_size: number;
            /**
             * Save Checkpoints
             * @description Save checkpoints during training
             */
            save_checkpoints: boolean;
            /**
             * Checkpoint Id
             * @description Optional custom identifier for the checkpoint
             */
            checkpoint_id?: string | null;
            /**
             * Use Device Gpu
             * @description Use GPU for training
             */
            use_device_GPU: boolean;
            /**
             * Device Id
             * @description GPU device ID
             */
            device_ID: number;
            /**
             * Jit Compile
             * @description Enable torch compile mode
             */
            jit_compile: boolean;
            /**
             * Jit Backend
             * @description Torch compile backend
             */
            jit_backend: string;
            /**
             * Use Mixed Precision
             * @description Enable mixed precision policy for GPU training
             */
            use_mixed_precision: boolean;
            /**
             * Dataloader Workers
             * @description DataLoader worker processes
             */
            dataloader_workers: number;
            /**
             * Prefetch Factor
             * @description DataLoader prefetch factor
             */
            prefetch_factor: number;
            /**
             * Pin Memory
             * @description Enable DataLoader pinned memory
             */
            pin_memory: boolean;
            /**
             * Persistent Workers
             * @description Keep DataLoader workers persistent across epochs
             */
            persistent_workers: boolean;
            /**
             * Plot Training Metrics
             * @description Generate training plots
             */
            plot_training_metrics: boolean;
            /**
             * Use Scheduler
             * @description Use learning rate scheduler
             */
            use_scheduler: boolean;
            /**
             * Target Lr
             * @description Target learning rate
             */
            target_LR: number;
            /**
             * Warmup Steps
             * @description Warmup steps for scheduler
             */
            warmup_steps: number;
        };
        /**
         * TextStatistics
         * @description Model for text statistics.
         */
        TextStatistics: {
            /** Count */
            count: number;
            /** Total Words */
            total_words: number;
            /** Unique Words */
            unique_words: number;
            /** Avg Words Per Report */
            avg_words_per_report: number;
            /** Min Words Per Report */
            min_words_per_report: number;
            /** Max Words Per Report */
            max_words_per_report: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ValidationReportResponse
         * @description Response model for a persisted validation report.
         */
        ValidationReportResponse: {
            /** Dataset Name */
            dataset_name: string;
            /** Date */
            date?: string | null;
            /** Sample Size */
            sample_size?: number | null;
            /** Metrics */
            metrics?: string[];
            pixel_distribution?: components["schemas"]["PixelDistribution"] | null;
            image_statistics?: components["schemas"]["ImageStatistics"] | null;
            text_statistics?: components["schemas"]["TextStatistics"] | null;
            /** Artifacts */
            artifacts?: {
                [key: string]: {
                    [key: string]: string;
                };
            } | null;
        };
        /**
         * ValidationRequest
         * @description Request model for dataset validation.
         */
        ValidationRequest: {
            /** Dataset Name */
            dataset_name: string;
            /** Metrics */
            metrics: string[];
            /** Sample Size */
            sample_size: number;
            /** Seed */
            seed?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_dataset_api_upload_dataset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_dataset_api_upload_dataset_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_status_api_preparation_dataset_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetStatusResponse"];
                };
            };
        };
    };
    get_dataset_names_api_preparation_dataset_names_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetNamesResponse"];
                };
            };
        };
    };
    get_processed_dataset_names_api_preparation_dataset_processed_names_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetNamesResponse"];
                };
            };
        };
    };
    get_processing_metadata_api_preparation_dataset_metadata__dataset_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingMetadataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dataset_api_preparation_dataset__dataset_name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_image_path_api_preparation_images_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImagePathRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImagePathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_dataset_api_preparation_dataset_load_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoadDatasetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadDatasetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_dataset_api_preparation_dataset_process_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcessDatasetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_image_count_api_preparation_dataset__dataset_name__images_count_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageCountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_image_metadata_api_preparation_dataset__dataset_name__images__index__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_name: string;
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageMetadataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_image_content_api_preparation_dataset__dataset_name__images__index__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_name: string;
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    browse_directory_api_preparation_browse_get: {
        parameters: {
            query?: {
                /** @description Directory path to browse. Empty returns drives. */
                path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_checkpoints_api_training_checkpoints_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckpointsResponse"];
                };
            };
        };
    };
    get_checkpoint_metadata_api_training_checkpoints__checkpoint__metadata_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                checkpoint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckpointMetadataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_checkpoint_api_training_checkpoints__checkpoint__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                checkpoint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_training_api_training_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartTrainingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_training_api_training_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeTrainingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_validation_api_validation_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_checkpoint_api_validation_checkpoint_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckpointEvaluationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_checkpoint_evaluation_report_api_validation_checkpoint_reports__checkpoint__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                checkpoint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckpointEvaluationReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_validation_report_api_validation_reports__dataset_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_models_api_inference_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InferenceModelsResponse"];
                };
            };
        };
    };
    check_model_update_api_inference_models_check_update_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelUpdateCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelUpdateCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    maintain_model_api_inference_models_maintenance_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelMaintenanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_reports_api_inference_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_generate_reports_api_inference_generate_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                job_type?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCancelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
