from __future__ import annotations

from sqlalchemy import Column, Float, Integer, String, UniqueConstraint

from XREPORT.server.repositories.database.base import Base
from XREPORT.server.repositories.schemas.types import JSONSequence


###############################################################################
class RadiographyData(Base):
    """Raw radiography images and their associated text reports."""

    __tablename__ = "radiography_data"
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String, nullable=False)
    image = Column(String, nullable=False)
    text = Column(String, nullable=False)
    path = Column(String)
    __table_args__ = (
        UniqueConstraint(
            "name",
            "image",
            "text",
            name="uq_radiography_data_name_image_text",
        ),
    )


###############################################################################
class TrainingData(Base):
    """Processed training dataset with tokenized text and train/val split."""

    __tablename__ = "training_dataset"
    id = Column(Integer, primary_key=True, autoincrement=True)
    hashcode = Column(String, nullable=False)
    name = Column(String)
    image = Column(String, nullable=False)
    text = Column(String, nullable=False)
    tokens = Column(JSONSequence)
    split = Column(String)
    path = Column(String)
    __table_args__ = (
        UniqueConstraint(
            "hashcode",
            "image",
            "text",
            name="uq_training_dataset_hashcode_image_text",
        ),
    )


###############################################################################
class ProcessingMetadata(Base):
    """Metadata for dataset preprocessing operations."""

    __tablename__ = "processing_metadata"
    hashcode = Column(String, primary_key=True, nullable=False)
    name = Column(String)
    source_dataset = Column(String)
    date = Column(String)
    seed = Column(Integer)
    sample_size = Column(Float)
    validation_size = Column(Float)
    split_seed = Column(Integer)
    vocabulary_size = Column(Integer)
    max_report_size = Column(Integer)
    tokenizer = Column(String)
    __table_args__ = (UniqueConstraint("hashcode"),)


###############################################################################
class GeneratedReport(Base):
    """Reports generated by the model during inference."""

    __tablename__ = "generated_reports"
    id = Column(Integer, primary_key=True, autoincrement=True)
    image = Column(String)
    report = Column(String)
    checkpoint = Column(String)
    __table_args__ = (UniqueConstraint("id"),)


###############################################################################
class ImageStatistics(Base):
    """Statistical analysis of images in the dataset."""

    __tablename__ = "image_statistics"
    dataset_name = Column(String, primary_key=True)
    name = Column(String, primary_key=True)
    height = Column(Integer)
    width = Column(Integer)
    mean = Column(Float)
    median = Column(Float)
    std = Column(Float)
    min = Column(Float)
    max = Column(Float)
    pixel_range = Column(Float)
    noise_std = Column(Float)
    noise_ratio = Column(Float)
    __table_args__ = (UniqueConstraint("dataset_name", "name"),)


###############################################################################
class TextStatistics(Base):
    """Statistical analysis of text reports in the dataset."""

    __tablename__ = "text_statistics"
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String)
    words_count = Column(Integer)
    __table_args__ = (UniqueConstraint("id"),)


###############################################################################
class ValidationReport(Base):
    """Aggregated validation report payloads for datasets."""

    __tablename__ = "validation_reports"
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String)
    date = Column(String)
    sample_size = Column(Float)
    metrics = Column(JSONSequence)
    text_statistics = Column(JSONSequence)
    image_statistics = Column(JSONSequence)
    pixel_distribution = Column(JSONSequence)
    artifacts = Column(JSONSequence)
    __table_args__ = (UniqueConstraint("id"),)


###############################################################################
class CheckpointEvaluationReport(Base):
    """Aggregated evaluation report payloads for checkpoints."""

    __tablename__ = "checkpoint_evaluation_reports"
    id = Column(Integer, primary_key=True, autoincrement=True)
    checkpoint = Column(String)
    date = Column(String)
    metrics = Column(JSONSequence)
    metric_configs = Column(JSONSequence)
    results = Column(JSONSequence)
    __table_args__ = (UniqueConstraint("id"),)
