import { useState, useRef, DragEvent, ChangeEvent } from 'react';
import {
    ImagePlus, ChevronLeft, ChevronRight, Trash2, FileText,
    Sparkles, ArrowRight, Copy, Check, Loader2
} from 'lucide-react';
import './InferencePage.css';

// Mock report for demonstration
const MOCK_REPORT = `# Radiological Report

## Patient Information
**Study Type:** Chest X-Ray (PA View)  
**Date:** December 17, 2025

## Findings

### Lungs
- Both lung fields are clear with no evidence of consolidation, mass lesion, or pleural effusion
- Normal lung markings are preserved bilaterally
- No pneumothorax identified

### Heart & Mediastinum
- Cardiac silhouette is within normal limits
- Mediastinal contours are unremarkable
- No hilar enlargement noted

### Bones & Soft Tissues
- Visualized osseous structures show no acute abnormality
- Soft tissues are unremarkable

### Diaphragm
- Both hemidiaphragms are well-defined
- Costophrenic angles are sharp bilaterally

## Impression
1. **Normal chest radiograph**
2. No acute cardiopulmonary disease identified

---
*This report was generated by XREPORT AI Assistant*
`;

export default function InferencePage() {
    // Image state
    const [images, setImages] = useState<File[]>([]);
    const [currentIndex, setCurrentIndex] = useState(0);
    const [isDragging, setIsDragging] = useState(false);
    const fileInputRef = useRef<HTMLInputElement>(null);

    // Report state
    const [generatedReport, setGeneratedReport] = useState<string>('');
    const [isGenerating, setIsGenerating] = useState(false);
    const [isCopied, setIsCopied] = useState(false);

    // Handle file selection
    const handleFileSelect = (files: FileList | null) => {
        if (!files || files.length === 0) return;

        const imageFiles = Array.from(files).filter(file =>
            file.type.startsWith('image/')
        );

        if (imageFiles.length > 0) {
            setImages(imageFiles);
            setCurrentIndex(0);
            setGeneratedReport('');
        }
    };

    // Drag and drop handlers
    const handleDragOver = (e: DragEvent<HTMLDivElement>) => {
        e.preventDefault();
        setIsDragging(true);
    };

    const handleDragLeave = (e: DragEvent<HTMLDivElement>) => {
        e.preventDefault();
        setIsDragging(false);
    };

    const handleDrop = (e: DragEvent<HTMLDivElement>) => {
        e.preventDefault();
        setIsDragging(false);
        handleFileSelect(e.dataTransfer.files);
    };

    const handleInputChange = (e: ChangeEvent<HTMLInputElement>) => {
        handleFileSelect(e.target.files);
    };

    const openFileDialog = () => {
        fileInputRef.current?.click();
    };

    // Navigation
    const goToPrevious = () => {
        setCurrentIndex(prev => Math.max(0, prev - 1));
    };

    const goToNext = () => {
        setCurrentIndex(prev => Math.min(images.length - 1, prev + 1));
    };

    // Clear images
    const clearImages = () => {
        setImages([]);
        setCurrentIndex(0);
        setGeneratedReport('');
        if (fileInputRef.current) {
            fileInputRef.current.value = '';
        }
    };

    // Generate report (mock)
    const handleGenerateReport = async () => {
        if (images.length === 0) return;

        setIsGenerating(true);

        // Simulate API call
        await new Promise(resolve => setTimeout(resolve, 2000));

        setGeneratedReport(MOCK_REPORT);
        setIsGenerating(false);
    };

    // Copy report to clipboard
    const copyReport = async () => {
        if (!generatedReport) return;

        try {
            await navigator.clipboard.writeText(generatedReport);
            setIsCopied(true);
            setTimeout(() => setIsCopied(false), 2000);
        } catch (err) {
            console.error('Failed to copy:', err);
        }
    };

    // Get current image URL
    const currentImageUrl = images.length > 0
        ? URL.createObjectURL(images[currentIndex])
        : null;

    return (
        <div className="inference-container">
            <div className="inference-header">
                <h1>Inference</h1>
                <p>Generate radiological reports from X-ray scans using AI</p>
            </div>

            <div className="inference-main">
                {/* Left Column - Image Canvas */}
                <div className="inference-panel">
                    <div className="panel-header">
                        <ImagePlus size={18} />
                        <h2>X-Ray Images</h2>
                    </div>
                    <div className="panel-content">
                        {images.length === 0 ? (
                            <div
                                className={`image-dropzone ${isDragging ? 'dragging' : ''}`}
                                onDragOver={handleDragOver}
                                onDragLeave={handleDragLeave}
                                onDrop={handleDrop}
                                onClick={openFileDialog}
                            >
                                <ImagePlus className="dropzone-icon" />
                                <div className="dropzone-text">
                                    <div className="dropzone-title">
                                        Drop images here or click to upload
                                    </div>
                                    <div className="dropzone-subtitle">
                                        Supports single or multiple X-ray images
                                    </div>
                                </div>
                                <input
                                    ref={fileInputRef}
                                    type="file"
                                    accept="image/*"
                                    multiple
                                    onChange={handleInputChange}
                                    style={{ display: 'none' }}
                                />
                            </div>
                        ) : (
                            <div className="image-viewer">
                                <div className="image-display">
                                    {currentImageUrl && (
                                        <img
                                            src={currentImageUrl}
                                            alt={`X-ray ${currentIndex + 1}`}
                                        />
                                    )}

                                    {images.length > 1 && (
                                        <>
                                            <button
                                                className="nav-arrow prev"
                                                onClick={goToPrevious}
                                                disabled={currentIndex === 0}
                                            >
                                                <ChevronLeft size={20} />
                                            </button>
                                            <button
                                                className="nav-arrow next"
                                                onClick={goToNext}
                                                disabled={currentIndex === images.length - 1}
                                            >
                                                <ChevronRight size={20} />
                                            </button>
                                            <div className="image-counter">
                                                {currentIndex + 1} / {images.length}
                                            </div>
                                        </>
                                    )}
                                </div>

                                <div className="image-controls">
                                    <button
                                        className="btn-icon"
                                        onClick={openFileDialog}
                                        title="Add more images"
                                    >
                                        <ImagePlus />
                                    </button>
                                    <button
                                        className="btn-icon"
                                        onClick={clearImages}
                                        title="Clear all images"
                                    >
                                        <Trash2 />
                                    </button>
                                </div>

                                <input
                                    ref={fileInputRef}
                                    type="file"
                                    accept="image/*"
                                    multiple
                                    onChange={handleInputChange}
                                    style={{ display: 'none' }}
                                />
                            </div>
                        )}
                    </div>
                </div>

                {/* Center Column - Flow Connector */}
                <div className="flow-panel">
                    <div className="flow-connector">
                        <div className="flow-arrow">
                            <ArrowRight size={24} />
                            <ArrowRight size={24} />
                            <ArrowRight size={24} />
                        </div>

                        <button
                            className={`btn-generate ${isGenerating ? 'generating' : ''}`}
                            onClick={handleGenerateReport}
                            disabled={images.length === 0 || isGenerating}
                        >
                            {isGenerating ? (
                                <Loader2 className="loading-spinner" />
                            ) : (
                                <Sparkles />
                            )}
                            <span>
                                {isGenerating ? 'Generating...' : 'Generate Report'}
                            </span>
                        </button>

                        <div className="flow-arrow">
                            <ArrowRight size={24} />
                            <ArrowRight size={24} />
                            <ArrowRight size={24} />
                        </div>
                    </div>
                </div>

                {/* Right Column - Report Viewer */}
                <div className="inference-panel">
                    <div className="panel-header">
                        <div className="report-header">
                            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                                <FileText size={18} />
                                <h2>Generated Report</h2>
                            </div>
                            {generatedReport && (
                                <div className="report-actions">
                                    <button
                                        className="btn-icon"
                                        onClick={copyReport}
                                        title="Copy to clipboard"
                                    >
                                        {isCopied ? <Check /> : <Copy />}
                                    </button>
                                </div>
                            )}
                        </div>
                    </div>
                    <div className="panel-content">
                        {generatedReport ? (
                            <div className="report-content">
                                <div
                                    className="markdown-report"
                                    dangerouslySetInnerHTML={{
                                        __html: formatMarkdown(generatedReport)
                                    }}
                                />
                            </div>
                        ) : (
                            <div className="report-empty">
                                <FileText />
                                <p>
                                    {images.length === 0
                                        ? 'Upload X-ray images to generate a report'
                                        : 'Click "Generate Report" to analyze the images'}
                                </p>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
}

// Simple markdown formatter (basic implementation)
function formatMarkdown(text: string): string {
    return text
        // Headers
        .replace(/^### (.*$)/gm, '<h3>$1</h3>')
        .replace(/^## (.*$)/gm, '<h2>$1</h2>')
        .replace(/^# (.*$)/gm, '<h1>$1</h1>')
        // Bold
        .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
        // Italic
        .replace(/\*(.*?)\*/g, '<em>$1</em>')
        // Code
        .replace(/`(.*?)`/g, '<code>$1</code>')
        // Horizontal rule
        .replace(/^---$/gm, '<hr />')
        // Unordered list items
        .replace(/^- (.*$)/gm, '<li>$1</li>')
        // Wrap consecutive list items in ul
        .replace(/(<li>.*<\/li>\n?)+/g, '<ul>$&</ul>')
        // Line breaks for paragraphs
        .replace(/\n\n/g, '</p><p>')
        // Wrap in paragraph
        .replace(/^(.+)$/gm, (match) => {
            if (match.startsWith('<')) return match;
            return match;
        });
}
