fn main() {
    tauri_build::build();

    let manifest_dir = std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let generated = manifest_dir.join("generated");
    std::fs::create_dir_all(&generated).expect("create generated runtime directory");
    let archive = generated.join("runtime.zip");
    if !archive.exists() {
        // Development builds have no frozen backend yet.  The release
        // launcher replaces this placeholder before invoking `tauri build`.
        std::fs::write(
            &archive,
            b"XREPORT runtime archive is generated by BuildDesktopRelease",
        )
        .expect("create runtime archive placeholder");
    }
    let variant = std::env::var("XREPORT_DESKTOP_VARIANT").unwrap_or_else(|_| "cpu".to_string());
    println!("cargo:rustc-env=XREPORT_DESKTOP_VARIANT={variant}");
    println!("cargo:rerun-if-changed=generated/runtime.zip");
    println!("cargo:rerun-if-changed=ui");
}
