from __future__ import annotations

from sqlalchemy import (
    Column,
    Float,
    Integer,
    String,
    UniqueConstraint,
)
from sqlalchemy.orm import declarative_base

Base = declarative_base()


###############################################################################
class RadiographyData(Base):
    """Raw radiography images and their associated text reports."""
    __tablename__ = "RADIOGRAPHY_DATA"
    dataset_name = Column(String, primary_key=True)
    id = Column(Integer, primary_key=True)
    image = Column(String)
    text = Column(String)
    path = Column(String)  # Full path to image file
    __table_args__ = (UniqueConstraint("dataset_name", "id"),)


###############################################################################
class TrainingData(Base):
    """Processed training dataset with tokenized text and train/val split."""
    __tablename__ = "TRAINING_DATASET"
    image = Column(String, primary_key=True)
    text = Column(String)
    tokens = Column(String)
    split = Column(String)
    path = Column(String)  # Full image path for training
    __table_args__ = (UniqueConstraint("image"),)


###############################################################################
class ProcessingMetadata(Base):
    """Metadata for dataset preprocessing operations."""
    __tablename__ = "PROCESSING_METADATA"
    dataset_name = Column(String, primary_key=True)
    date = Column(String)
    seed = Column(Integer)
    sample_size = Column(Float)
    validation_size = Column(Float)
    split_seed = Column(Integer)
    vocabulary_size = Column(Integer)
    max_report_size = Column(Integer)
    tokenizer = Column(String)
    __table_args__ = (UniqueConstraint("dataset_name"),)


###############################################################################
class GeneratedReport(Base):
    """Reports generated by the model during inference."""
    __tablename__ = "GENERATED_REPORTS"
    image = Column(String, primary_key=True)
    report = Column(String)
    checkpoint = Column(String, primary_key=True)
    __table_args__ = (UniqueConstraint("image", "checkpoint"),)


###############################################################################
class ImageStatistics(Base):
    """Statistical analysis of images in the dataset."""
    __tablename__ = "IMAGE_STATISTICS"
    dataset_name = Column(String, primary_key=True)
    name = Column(String, primary_key=True)
    height = Column(Integer)
    width = Column(Integer)
    mean = Column(Float)
    median = Column(Float)
    std = Column(Float)
    min = Column(Float)
    max = Column(Float)
    pixel_range = Column(Float)
    noise_std = Column(Float)
    noise_ratio = Column(Float)
    __table_args__ = (UniqueConstraint("dataset_name", "name"),)


###############################################################################
class TextStatistics(Base):
    """Statistical analysis of text reports in the dataset."""
    __tablename__ = "TEXT_STATISTICS"
    dataset_name = Column(String, primary_key=True)
    name = Column(String, primary_key=True)
    words_count = Column(Integer)
    __table_args__ = (UniqueConstraint("dataset_name", "name"),)


###############################################################################
class CheckpointSummary(Base):
    """Training checkpoint metadata and performance metrics."""
    __tablename__ = "CHECKPOINTS_SUMMARY"
    checkpoint = Column(String, primary_key=True)
    sample_size = Column(Float)
    validation_size = Column(Float)
    seed = Column(Integer)
    precision = Column(Integer)
    epochs = Column(Integer)
    batch_size = Column(Integer)
    split_seed = Column(Integer)
    image_augmentation = Column(String)
    image_height = Column(Integer)
    image_width = Column(Integer)
    image_channels = Column(Integer)
    jit_compile = Column(String)
    has_tensorboard_logs = Column(String)
    post_warmup_LR = Column(Float)
    warmup_steps = Column(Float)
    temperature = Column(Float)
    tokenizer = Column(String)
    max_report_size = Column(Integer)
    attention_heads = Column(Integer)
    n_encoders = Column(Integer)
    n_decoders = Column(Integer)
    embedding_dimensions = Column(Integer)
    frozen_img_encoder = Column(String)
    train_loss = Column(Float)
    val_loss = Column(Float)
    train_accuracy = Column(Float)
    val_accuracy = Column(Float)
    __table_args__ = (UniqueConstraint("checkpoint"),)
