import { CommonModule } from '@angular/common';
import { Component, computed, DestroyRef, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormsModule } from '@angular/forms';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideActivity, lucideBarChart2, lucideChevronDown, lucideChevronUp, lucideInfo, lucideLoaderCircle, lucidePlay, lucideRefreshCw, lucideRotateCcw, lucideTrash2, lucideX } from '@ng-icons/lucide';
import { asRecord, readNumber } from '../common/parsers';
import { ApiService } from '../services/api.service';
import { AppStateService } from '../services/app-state.service';
import { JobPollingService } from '../services/job-polling.service';
import { StorageService } from '../services/storage.service';
import type { CheckpointInfo, DatasetInfo, StartTrainingConfig } from '../types/trainingApi';

const EVALUATION_STORAGE_KEY = 'xreport.checkpoint_evaluation.jobs';
interface StoredEvaluationJob { jobId: string; metrics: string[]; status?: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled'; progress?: number; }

@Component({
  standalone: true,
  selector: 'app-training-page',
  imports: [CommonModule, FormsModule, NgIcon],
  providers: [provideIcons({ lucideActivity, lucideBarChart2, lucideChevronDown, lucideChevronUp, lucideInfo, lucideLoaderCircle, lucidePlay, lucideRefreshCw, lucideRotateCcw, lucideTrash2, lucideX })],
  template: `
    <main class="training-container"><div class="header"><h1>XREPORT Transformer</h1><p>Configure and monitor your training sessions</p></div><div class="training-panels">
      <section class="training-panel" [class.collapsed]="collapsedNew()"><div class="panel-left"><div class="panel-header"><div><h3>New Training Session</h3><p>Select a processed dataset to configure your next run.</p></div><button type="button" class="panel-collapse-toggle" [attr.aria-expanded]="!collapsedNew()" (click)="collapsedNew.set(!collapsedNew())"><ng-icon [name]="collapsedNew() ? 'lucideChevronDown' : 'lucideChevronUp'"/></button><button type="button" class="panel-refresh" title="Refresh datasets" (click)="loadDatasets()"><ng-icon name="lucideRefreshCw"/></button></div>@if (!collapsedNew()) { <div class="panel-collapsible-content"><div class="panel-list">@if (!datasets().length) { <div class="panel-empty">No datasets available yet.</div> }@for (dataset of datasets(); track dataset.name) { <div class="panel-row" [class.selected]="selectedDataset()?.name === dataset.name"><button type="button" class="panel-row-main panel-row-main-button" [attr.aria-pressed]="selectedDataset()?.name === dataset.name" (click)="selectDataset(dataset)"><span class="panel-row-title">{{ dataset.name }}</span><span class="panel-row-count">{{ dataset.row_count | number }} rows</span></button><div class="panel-row-actions"><button type="button" class="icon-button" title="Show metadata" (click)="showDatasetMetadata(dataset)"><ng-icon name="lucideInfo"/></button><button type="button" class="icon-button danger" title="Delete dataset" (click)="deleteDataset(dataset)"><ng-icon name="lucideTrash2"/></button></div></div> }</div></div> }</div><div class="panel-right"><div class="panel-card"><div class="panel-card-header"><div class="panel-card-title-row"><ng-icon name="lucidePlay"/><h4>Initialize Training</h4></div><p>Launch the configuration wizard to set up your training run.</p></div><div class="panel-card-summary"><span>Selected Dataset</span><strong>{{ selectedDataset()?.name || 'None selected' }}</strong><span>Samples</span><strong>{{ selectedDataset() ? (selectedDataset()!.row_count | number) : 'N/A' }}</strong></div><button type="button" class="btn btn-primary" (click)="newWizardOpen.set(true)" [disabled]="!selectedDataset()"><ng-icon name="lucidePlay"/>Configure Training</button></div></div></section>
      <section class="training-panel" [class.collapsed]="collapsedResume()"><div class="panel-left"><div class="panel-header"><div><h3>Resume Training</h3><p>Pick a checkpoint to continue training from a saved state.</p></div><button type="button" class="panel-collapse-toggle" [attr.aria-expanded]="!collapsedResume()" (click)="collapsedResume.set(!collapsedResume())"><ng-icon [name]="collapsedResume() ? 'lucideChevronDown' : 'lucideChevronUp'"/></button><button type="button" class="panel-refresh" title="Refresh checkpoints" (click)="loadCheckpoints()"><ng-icon name="lucideRefreshCw"/></button></div>@if (!collapsedResume()) { <div class="panel-collapsible-content"><div class="panel-list">@if (!checkpoints().length) { <div class="panel-empty">No checkpoints available yet.</div> }@for (checkpoint of checkpoints(); track checkpoint.name) { <div class="panel-row" [class.selected]="selectedCheckpoint() === checkpoint.name"><button type="button" class="panel-row-main panel-row-main-button" [attr.aria-pressed]="selectedCheckpoint() === checkpoint.name" (click)="selectedCheckpoint.set(checkpoint.name)"><span class="panel-row-title">{{ checkpoint.name }}</span><span class="panel-row-meta">{{ checkpoint.epochs }} epochs · loss {{ checkpoint.loss | number:'1.0-4' }}</span></button><div class="panel-row-actions"><button type="button" class="icon-button" title="Show metadata" (click)="showCheckpointMetadata(checkpoint)"><ng-icon name="lucideInfo"/></button><button type="button" class="icon-button" title="View evaluation report" (click)="openEvaluation(checkpoint)"><ng-icon name="lucideBarChart2"/></button><button type="button" class="icon-button danger" title="Delete checkpoint" (click)="deleteCheckpoint(checkpoint)"><ng-icon name="lucideTrash2"/></button></div></div> }</div></div> }</div><div class="panel-right"><div class="panel-card"><div class="panel-card-header"><div class="panel-card-title-row"><ng-icon name="lucideRotateCcw"/><h4>Checkpoint Actions</h4></div><p>Resume training or evaluate the performance of the selected checkpoint.</p></div><div class="panel-card-summary"><span>Selected Checkpoint</span><strong>{{ selectedCheckpoint() || 'None selected' }}</strong><span>Epochs</span><strong>{{ selectedCheckpointInfo()?.epochs || 'N/A' }}</strong></div><div class="panel-card-actions"><button type="button" class="btn btn-primary panel-card-action-btn" (click)="resumeWizardOpen.set(true)" [disabled]="!selectedCheckpoint()"><ng-icon name="lucideRotateCcw"/>Resume Training</button><button type="button" class="btn btn-secondary panel-card-action-btn" (click)="openEvaluation(selectedCheckpointInfo()!)" [disabled]="!selectedCheckpointInfo()"><ng-icon name="lucideActivity"/>Evaluate Model</button></div></div></div></section>
    </div><section class="training-dashboard"><div class="dashboard-header"><div><span class="eyebrow">Live session</span><h2>Training Dashboard</h2></div><span class="status-badge" [class.ready]="dashboard().isTraining">{{ dashboard().isTraining ? 'Running' : dashboard().currentEpoch ? 'Complete' : 'Idle' }}</span></div>@if (dashboard().isTraining) { <div class="training-progress"><div class="progress-heading"><span>Epoch {{ dashboard().currentEpoch }} / {{ dashboard().totalEpochs }}</span><strong>{{ dashboard().progressPercent | number:'1.0-0' }}%</strong></div><div class="progress-track"><span [style.width.%]="dashboard().progressPercent"></span></div><button type="button" class="btn btn-danger" (click)="stopTraining()">Stop training</button></div> }<div class="metrics-grid"><div><span>Loss</span><strong>{{ dashboard().loss | number:'1.0-4' }}</strong></div><div><span>Validation loss</span><strong>{{ dashboard().valLoss | number:'1.0-4' }}</strong></div><div><span>Accuracy</span><strong>{{ dashboard().accuracy | number:'1.0-3' }}</strong></div><div><span>Val accuracy</span><strong>{{ dashboard().valAccuracy | number:'1.0-3' }}</strong></div></div>@if (dashboard().logEntries.length) { <pre class="training-logs">{{ dashboard().logEntries.join('\n') }}</pre> }</section></main>
    @if (newWizardOpen()) { <div class="modal-backdrop" role="presentation"><section class="modal training-wizard-modal" role="dialog" aria-modal="true" aria-labelledby="new-training-title"><div class="modal-header"><h2 id="new-training-title">New Training Session</h2><button type="button" class="btn-icon-small" aria-label="Close" (click)="newWizardOpen.set(false)"><ng-icon name="lucideX"/></button></div><p>Configure the model and training schedule for <strong>{{ selectedDataset()?.name }}</strong>.</p><div class="form-grid training-form-grid"><label class="form-group"><span class="form-label">Epochs</span><input class="form-input" type="number" min="1" [(ngModel)]="trainingConfig.epochs"/></label><label class="form-group"><span class="form-label">Batch size</span><input class="form-input" type="number" min="1" [(ngModel)]="trainingConfig.batchSize"/></label><label class="form-group"><span class="form-label">Encoders</span><input class="form-input" type="number" min="1" [(ngModel)]="trainingConfig.numEncoders"/></label><label class="form-group"><span class="form-label">Decoders</span><input class="form-input" type="number" min="1" [(ngModel)]="trainingConfig.numDecoders"/></label><label class="form-group"><span class="form-label">Embedding dimensions</span><input class="form-input" type="number" min="1" [(ngModel)]="trainingConfig.embeddingDims"/></label><label class="form-group"><span class="form-label">Attention heads</span><input class="form-input" type="number" min="1" [(ngModel)]="trainingConfig.attnHeads"/></label></div>@if (trainingError()) { <div class="upload-status error">{{ trainingError() }}</div> }<div class="modal-footer"><button type="button" class="btn btn-secondary" (click)="newWizardOpen.set(false)">Cancel</button><button type="button" class="btn btn-primary" (click)="startTraining()" [disabled]="isLoading()"><ng-icon [name]="isLoading() ? 'lucideLoaderCircle' : 'lucidePlay'" [class.spin]="isLoading()"/>Start training</button></div></section></div> }
    @if (resumeWizardOpen()) { <div class="modal-backdrop" role="presentation"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="resume-title"><div class="modal-header"><h2 id="resume-title">Resume Training</h2><button type="button" class="btn-icon-small" aria-label="Close" (click)="resumeWizardOpen.set(false)"><ng-icon name="lucideX"/></button></div><p>Continue from <strong>{{ selectedCheckpoint() }}</strong>.</p><label class="form-group"><span class="form-label">Additional epochs</span><input class="form-input" type="number" min="1" [(ngModel)]="additionalEpochs"/></label>@if (trainingError()) { <div class="upload-status error">{{ trainingError() }}</div> }<div class="modal-footer"><button type="button" class="btn btn-secondary" (click)="resumeWizardOpen.set(false)">Cancel</button><button type="button" class="btn btn-primary" (click)="resumeTraining()" [disabled]="isLoading()">Resume training</button></div></section></div> }
    @if (evaluationOpen()) { <div class="modal-backdrop" role="presentation"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="evaluation-title"><div class="modal-header"><h2 id="evaluation-title">Checkpoint Evaluation</h2><button type="button" class="btn-icon-small" aria-label="Close" (click)="evaluationOpen.set(false)"><ng-icon name="lucideX"/></button></div><p>Evaluate <strong>{{ evaluationCheckpoint()?.name }}</strong> against the processed validation set.</p><label class="checkbox-label"><input type="checkbox" [(ngModel)]="evaluationMetrics.evaluationReport"/> Evaluation report</label><label class="checkbox-label"><input type="checkbox" [(ngModel)]="evaluationMetrics.bleuScore"/> BLEU score</label>@if (evaluationStatus()) { <div class="upload-status" [class.success]="evaluationStatus() === 'completed'" [class.error]="evaluationStatus() === 'failed'">{{ evaluationStatus() }}</div> }<div class="modal-footer"><button type="button" class="btn btn-secondary" (click)="evaluationOpen.set(false)">Close</button><button type="button" class="btn btn-primary" (click)="runEvaluation()" [disabled]="evaluationBusy()">{{ evaluationBusy() ? 'Evaluating…' : 'Run evaluation' }}</button></div></section></div> }
    @if (metadataModal()) { <div class="modal-backdrop" role="presentation"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="metadata-title"><div class="modal-header"><h2 id="metadata-title">{{ metadataModal()?.title }}</h2><button type="button" class="btn-icon-small" aria-label="Close" (click)="metadataModal.set(null)"><ng-icon name="lucideX"/></button></div><p>{{ metadataModal()?.subtitle }}</p><pre>{{ metadataModal()?.body }}</pre></section></div> }
  `,
  styleUrl: '../styles/TrainingPage.css',
})
export class TrainingPage {
  private readonly api = inject(ApiService);
  private readonly appState = inject(AppStateService);
  private readonly polling = inject(JobPollingService);
  private readonly storage = inject(StorageService);
  private readonly destroyRef = inject(DestroyRef);
  readonly state = this.appState.training;
  readonly datasets = signal<DatasetInfo[]>([]);
  readonly checkpoints = signal<CheckpointInfo[]>([]);
  readonly selectedDataset = signal<DatasetInfo | null>(null);
  readonly selectedCheckpoint = signal('');
  readonly collapsedNew = signal(false);
  readonly collapsedResume = signal(false);
  readonly newWizardOpen = signal(false);
  readonly resumeWizardOpen = signal(false);
  readonly evaluationOpen = signal(false);
  readonly metadataModal = signal<{ title: string; subtitle: string; body: string } | null>(null);
  readonly isLoading = signal(false);
  readonly trainingError = signal<string | null>(null);
  readonly evaluationBusy = signal(false);
  readonly evaluationStatus = signal<string | null>(null);
  readonly evaluationCheckpoint = signal<CheckpointInfo | null>(null);
  readonly evaluationJobs = signal<Record<string, StoredEvaluationJob>>(this.storage.readRecord<StoredEvaluationJob>(EVALUATION_STORAGE_KEY));
  readonly evaluationMetrics = { evaluationReport: true, bleuScore: false };
  additionalEpochs = 50;
  trainingConfig = { ...this.state().config };
  readonly dashboard = computed(() => this.state().dashboardState);
  readonly selectedCheckpointInfo = computed(() => this.checkpoints().find((checkpoint) => checkpoint.name === this.selectedCheckpoint()) ?? null);
  constructor() { void this.loadDatasets(); void this.loadCheckpoints(); }
  async loadDatasets() { const result = await this.api.getProcessedDatasetNames(); if (result.result) this.datasets.set(result.result.datasets); }
  async loadCheckpoints() { const result = await this.api.getCheckpoints(); if (result.result) this.checkpoints.set(result.result.checkpoints); }
  selectDataset(dataset: DatasetInfo) { this.selectedDataset.set(dataset); }
  async showDatasetMetadata(dataset: DatasetInfo) { const result = await this.api.getProcessingMetadata(dataset.name); this.metadataModal.set({ title: 'Dataset Metadata', subtitle: dataset.name, body: result.result ? JSON.stringify(result.result.metadata, null, 2) : result.error ?? 'No metadata found' }); }
  async deleteDataset(dataset: DatasetInfo) { if (!confirm(`Delete dataset "${dataset.name}"? This cannot be undone.`)) return; const result = await this.api.deleteDataset(dataset.name); if (!result.result) this.trainingError.set(result.error); await this.loadDatasets(); }
  async showCheckpointMetadata(checkpoint: CheckpointInfo) { const result = await this.api.getCheckpointMetadata(checkpoint.name); this.metadataModal.set({ title: 'Checkpoint Metadata', subtitle: checkpoint.name, body: result.result ? JSON.stringify(result.result, null, 2) : result.error ?? 'No metadata found' }); }
  async deleteCheckpoint(checkpoint: CheckpointInfo) { if (!confirm(`Delete checkpoint "${checkpoint.name}"? This cannot be undone.`)) return; const result = await this.api.deleteCheckpoint(checkpoint.name); if (!result.result) this.trainingError.set(result.error); await this.loadCheckpoints(); }
  private startConfig(checkpointId?: string): StartTrainingConfig { const config = this.trainingConfig; return { dataset_name: this.selectedDataset()?.name ?? '', epochs: config.epochs, batch_size: config.batchSize, num_encoders: config.numEncoders, num_decoders: config.numDecoders, embedding_dims: config.embeddingDims, attention_heads: config.attnHeads, train_temp: config.trainTemp, freeze_img_encoder: config.freezeImgEncoder, use_img_augmentation: config.useImgAugment, shuffle_with_buffer: config.shuffleWithBuffer, shuffle_size: config.shuffleBufferSize, save_checkpoints: config.saveCheckpoints, checkpoint_id: checkpointId, use_device_GPU: config.useGpu, device_ID: config.gpuId, jit_compile: config.jitCompile, jit_backend: config.jitBackend, use_mixed_precision: config.useMixedPrecision, dataloader_workers: config.dataloaderWorkers, prefetch_factor: config.prefetchFactor, pin_memory: config.pinMemory, persistent_workers: config.persistentWorkers, plot_training_metrics: config.realTimePlot, use_scheduler: config.useScheduler, target_LR: config.targetLR, warmup_steps: config.warmupSteps }; }
  async startTraining() { if (!this.selectedDataset()) return; this.isLoading.set(true); this.trainingError.set(null); const started = await this.api.startTraining(this.startConfig()); if (!started.result) { this.isLoading.set(false); this.trainingError.set(started.error ?? 'Training failed'); return; } this.newWizardOpen.set(false); this.isLoading.set(false); this.pollTraining(started.result.job_id); }
  async resumeTraining() { if (!this.selectedCheckpoint()) return; this.isLoading.set(true); const started = await this.api.resumeTraining(this.selectedCheckpoint(), Math.max(1, Math.trunc(this.additionalEpochs))); if (!started.result) { this.isLoading.set(false); this.trainingError.set(started.error ?? 'Resume training failed'); return; } this.resumeWizardOpen.set(false); this.isLoading.set(false); this.pollTraining(started.result.job_id); }
  private pollTraining(jobId: string) { this.appState.updateDashboard({ isTraining: true, currentEpoch: 0, progressPercent: 0, logEntries: [`Training job started (${jobId}).`] }); this.polling.poll((id) => this.api.getTrainingJobStatus(id), jobId, 2).pipe(takeUntilDestroyed(this.destroyRef)).subscribe((status) => { const result = asRecord(status.result); if (result) this.appState.updateDashboard({ isTraining: !['completed', 'failed', 'cancelled'].includes(status.status), currentEpoch: readNumber(result['current_epoch']), totalEpochs: readNumber(result['total_epochs']), loss: readNumber(result['loss']), valLoss: readNumber(result['val_loss']), accuracy: readNumber(result['accuracy']), valAccuracy: readNumber(result['val_accuracy']), progressPercent: readNumber(result['progress_percent']), elapsedSeconds: readNumber(result['elapsed_seconds']) }); if (['completed', 'failed', 'cancelled'].includes(status.status)) { this.appState.updateDashboard({ isTraining: false }); if (status.status !== 'completed') this.trainingError.set(status.error ?? `Training ${status.status}`); void this.loadCheckpoints(); } }); }
  async stopTraining() { const result = await this.api.getTrainingStatus(); if (result.result?.job_id) await this.api.cancelTrainingJob(result.result.job_id); this.appState.updateDashboard({ isTraining: false }); }
  openEvaluation(checkpoint: CheckpointInfo) { if (!checkpoint) return; this.evaluationCheckpoint.set(checkpoint); this.evaluationStatus.set(null); this.evaluationOpen.set(true); }
  async runEvaluation() { const checkpoint = this.evaluationCheckpoint(); if (!checkpoint) return; const metrics = [this.evaluationMetrics.evaluationReport ? 'evaluation_report' : '', this.evaluationMetrics.bleuScore ? 'bleu_score' : ''].filter(Boolean); if (!metrics.length) return; this.evaluationBusy.set(true); const started = await this.api.evaluateCheckpoint(checkpoint.name, metrics, 10, undefined, 42); if (!started.result) { this.evaluationBusy.set(false); this.evaluationStatus.set(started.error ?? 'Evaluation failed'); return; } this.evaluationJobs.update((jobs) => ({ ...jobs, [checkpoint.name]: { jobId: started.result!.job_id, metrics, status: 'pending' } })); this.storage.writeRecord(EVALUATION_STORAGE_KEY, this.evaluationJobs()); this.polling.poll((jobId) => this.api.getCheckpointEvaluationJobStatus(jobId), started.result.job_id, 2).pipe(takeUntilDestroyed(this.destroyRef)).subscribe((status) => { if (['completed', 'failed', 'cancelled'].includes(status.status)) { this.evaluationBusy.set(false); this.evaluationStatus.set(status.status); this.evaluationJobs.update((jobs) => ({ ...jobs, [checkpoint.name]: { ...(jobs[checkpoint.name]!), status: status.status, progress: status.progress } })); this.storage.writeRecord(EVALUATION_STORAGE_KEY, this.evaluationJobs()); } }); }
}

